version: 2.1

orbs:
  slack: circleci/slack@3.4.2

parameters:
  slack_channel:
    type: string
    default: '#cci-augmented-search'


references:
  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

defaults: &defaults
  working_directory: ~/source
  docker:
    - image: circleci/node:latest
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: yarn set version berry
      - run: yarn set version latest
      - run:
          name: Run lint and build
          command: yarn build

      - *persist-workspace
  test:
    <<: *defaults
    steps:
      - *attach-workspace

      - run:
          name: Run tests
          command: yarn test

      - *persist-workspace
  publish:
    <<: *defaults
    steps:
      - *attach-workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > ~/source/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public
      - slack/status:
          channel: << pipeline.parameters.slack_channel >>
          fail_only: true
          include_project_field: true
          include_visit_job_action: true
          mentions: "channel"

workflows:
  version: 2
  on-code-change:
    jobs:
      - build:
          context: QA_ENVIRONMENT
      - test:
          context: QA_ENVIRONMENT
          requires:
            - build
      - publish:
          context: QA_ENVIRONMENT
          requires:
            - test
          filters:
            branches:
              only:
                - master
