name: CI with yarn

on: [push]

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install & test with yarn
    - run: yarn install
    - run: yarn test
