name: CI with npm

on: [push]

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install & test with npm
      run: |
        npm install
        npm test --coverage
