name: On release
on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to npm
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '10.x'
        - name: Publish to npm
          run: |
            yarn install
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_PUBLISH_TOKEN }}" > .npmrc
            yarn publish --access public