name: On release
on:
    release:
        types: [published]

jobs:
    publish:
        name: Publish to npm
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
        - name: Publish to npm
          run: |
            yarn install
            yarn build
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_PUBLISH_TOKEN }}" > .npmrc
            yarn publish --access public
